"""initial application schema

Revision ID: 0e7b81141fb1
Revises: 
Create Date: 2026-10-07 06:57:01.744602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7b81141fb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('chatgpt_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('host_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('verifier', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state_hash')
    )
    op.create_table('post_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'generated', 'publishing', 'published', 'failed', 'cancelled', name='draftstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publishing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('slot')
    )
    op.create_table('post_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('x_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('host_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_sources',
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['post_drafts.id'], ),
    sa.PrimaryKeyConstraint('draft_id', 'article_id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'skipped', 'failed', 'uncertain', name='jobstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['post_drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot')
    )
    op.create_table('published_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('x_post_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['post_drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('draft_id'),
    sa.UniqueConstraint('x_post_id')
    )
    op.bulk_insert(sa.table(
        "sources", sa.column("name", sa.String), sa.column("url", sa.Text),
        sa.column("priority", sa.Integer), sa.column("enabled", sa.Boolean),
    ), [
        {"name": name, "url": url, "priority": priority, "enabled": True}
        for name, url, priority in [
            ("OpenAI", "https://openai.com/news/rss.xml", 30),
            ("GitHub", "https://github.blog/feed/", 30),
            ("Google", "https://developers.googleblog.com/feeds/posts/default", 20),
            ("Microsoft", "https://devblogs.microsoft.com/feed/", 20),
            ("Hugging Face", "https://huggingface.co/blog/feed.xml", 20),
            ("Zenn", "https://zenn.dev/topics/ai/feed", 10),
        ]
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_posts')
    op.drop_table('job_runs')
    op.drop_table('draft_sources')
    op.drop_table('x_credentials')
    op.drop_table('sources')
    op.drop_table('post_schedules')
    op.drop_table('post_drafts')
    op.drop_table('oauth_states')
    op.drop_table('chatgpt_credentials')
    op.drop_table('articles')
    # ### end Alembic commands ###
