"""bound reconciliation attempts

Revision ID: c3c067ee2e54
Revises: 0e7b81141fb1
Create Date: 2026-10-07 07:10:05.664470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c067ee2e54'
down_revision: Union[str, Sequence[str], None] = '0e7b81141fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_drafts', sa.Column('reconcile_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_drafts', 'reconcile_attempts')
    # ### end Alembic commands ###
